### ISSUE TITLE
Variable names with illegal Matlab characters

### ISSUE THREAD

**Issue by CristianaDim** [pupuis/sleepy#54]
The output fields from sleepy contain a dash (e.g., "sleepy-labels"), but Matlab only allows underscores in variable names (e.g., "sleepy_labels"), so even though importing in Matlab works, one cannot access/rename these variables.

**Comment by pupuis** [comment]
Accidentally closed by commit message. @CristianaDim: Please process and store a dataset with the latest master version. The data should now be stored in fields with underscores instead of hyphens. If you tested successfully I will create a new release.

**Comment by CristianaDim** [comment]
Hey @pupuis , I'm sorry, I didn't see the message... I tested and it works now. Thank you so much!
