### ISSUE TITLE
Removing branch "relative"

### ISSUE THREAD

**Issue by pupuis** [pupuis/sleepy#55]
Hi @CristianaDim,

in an attempt to clean up the repository I removed all deprecated/unused remote branches, except for master and your branch, "relative". With you permission I would also like to remove that branch as I am pretty sure all changes were merged into master. 

Can you confirm this? If yes, please notify me really quick, so I can remove the branch too.

Thank you.

**Comment by CristianaDim** [comment]
Hi @pupuis,

Sure, you can remove this branch as well.

Best,
Cristiana
